### ISSUE TITLE
Error while using Zoom To

### ISSUE THREAD

**Issue by gonzayb** [darklordgrep/Mapbits#6]
I'm having this message in my Console when I execute Zoom To DA:
Uncaught Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, an object {lon: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]
    at Gu.convert (maplibre-gl.js?v=24.1.0:42:273645)
    at V.setSouthWest (maplibre-gl.js?v=24.1.0:46:24060)
    at new V (maplibre-gl.js?v=24.1.0:46:23855)
    at V.convert (maplibre-gl.js?v=24.1.0:46:25402)
    at t.Map.cameraForBounds (maplibre-gl.js?v=24.1.0:46:313710)
    at t.Map.fitBounds (maplibre-gl.js?v=24.1.0:46:315024)
    at Object.success [as callback] (mapbits-zoomto.js:33:15)
    at desktop_all.min.js?v=24.1.0:21:10741
    at s.trigger.L.success (desktop_all.min.js?v=24.1.0:21:10872)
    at c (desktop_all.min.js?v=24.1.0:5:28402)

My settings are these:
Query Type: GeoJSON (also tried with SDO_GEOMETRY)

Query Returning Extent Geometry:
SELECT sdo_util.to_geojson(sdo_geom.sdo_mbr(GEOMETRIA))
FROM LTW_LOTES
WHERE ID_FRACCION = :P690_ID_FRACCION 
AND COD_LOTE = 1
AND ID_MANZANA = 1;

The result of this query is:
{ "type": "Polygon", "coordinates": [ [ [-57.1175055005417, -25.4281218365096], [-57.1172262385873, -25.4281218365096], [-57.1172262385873, -25.427881095522], [-57.1175055005417, -25.427881095522], [-57.1175055005417, -25.4281218365096] ] ] }

Page Item to Submit: :P690_ID_FRACCION 

Affected Region: Consulta de Lotes (The one with the map)

Apex 24.1

**Comment by darklordgrep** [comment]
Is your dynamic action triggered from a 'Page Load' or 'Map Initialized' event? Do you have the Zoom To dynamic action's 'fires on initialization' setting turned on? 

I may have just fixed this issue. Give the latest version a try and let me know if you still see the error.

**Comment by gonzayb** [comment]
> Is your dynamic action triggered from a 'Page Load' or 'Map Initialized' event? Do you have the Zoom To dynamic action's 'fires on initialization' setting turned on?
> 
> I may have just fixed this issue. Give the latest version a try and let me know if you still see the error.

Tried the latest version but it still doesn't work yet.

Sorry but I'm not using DA triggered from Page Load or Map Initialized. It doesn't fires on initialization either. I have the DA on a Change event, when I change the 'P690_ID_FRACCION' item.

But I'm getting a new error:
mapbits-zoomto.js:32 Uncaught Error: Error fitting bounds. Check that the map region and Zoom To plugin are properly configured.
    at Object.success [as callback] (mapbits-zoomto.js:32:19)
    at desktop_all.min.js?v=24.1.0:21:10741
    at s.trigger.L.success (desktop_all.min.js?v=24.1.0:21:10872)
    at c (desktop_all.min.js?v=24.1.0:5:28402)
    at Object.fireWith [as resolveWith] (desktop_all.min.js?v=24.1.0:5:29150)
    at S (desktop_all.min.js?v=24.1.0:5:80183)
    at XMLHttpRequest.<anonymous> (desktop_all.min.js?v=24.1.0:5:82651)

My settings are the same as the last time. I double-checked my item and settings.

Is there something else I should try?

**Comment by darklordgrep** [comment]
I have not been able to reproduce the problem yet. The plugin uses an ajax process to query the bounding box. Could you use a web browser debugger and look at the network HTTP calls to see what 'response' you get from the ajax process? The ajax call should have 'zoom-to' in the name. See below for example:

![Image](https://github.com/user-attachments/assets/93fee024-bfd5-4830-a261-0c171aa7767e)

**Comment by gonzayb** [comment]
![Image](https://github.com/user-attachments/assets/88bf06ed-fdae-4337-a699-d49e3b6d1360)

I tried several things to turn those commas back to points again but nothing seems to work, I get errors in my AJAX response or they just stay as they are in the screenshot. Any ideas? Maybe it has to do with the region (location) of my application but I can change that

**Comment by jameswestman-work** [comment]
This might have been a bug that occurred when the padding attribute was blank. I pushed a fixed version of the DA plugin export (not in the demo app, just in APEX_Map_Region_Accessory_Plugins/dynamic_action_plugin_mil_army_usace_mapbits_zoom_to.sql). Does importing that plugin fix the issue?

**Comment by gonzayb** [comment]
Hi, I tried the latest version of the plugin but the issue is still there.
I ended up finding another way to achieve the same effect using JavaScript:

```
apex.region("region_grafico").call("setCenter", [centerLat, centerLon]);
apex.region("region_grafico").call("setZoomLevel", 16);
```

I still believe the root cause is related to the regional settings of my APEX instance/server.
What actually happens is that the decimal points in the coordinates are turned into commas, and then when the JSON is formatted, those commas are interpreted as separators and get replaced by line breaks. This ends up producing an invalid JSON for fitBounds.

**Comment by jameswestman-work** [comment]
Ok, should be fixed now. I changed it to use APEX_JAVASCRIPT.ADD_ATTRIBUTE which should format it correctly.
